/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author acer
 */
public class homeadmin extends javax.swing.JFrame {

    /**
     * Creates new form homeadmin
     */
    public homeadmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrafik = new javax.swing.JButton();
        btnkasir = new javax.swing.JButton();
        btnlaporan = new javax.swing.JButton();
        ubahharga = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btngrafik.setBorderPainted(false);
        btngrafik.setContentAreaFilled(false);
        btngrafik.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btngrafik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrafikActionPerformed(evt);
            }
        });
        getContentPane().add(btngrafik, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 420, 220));

        btnkasir.setBorderPainted(false);
        btnkasir.setContentAreaFilled(false);
        btnkasir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnkasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkasirActionPerformed(evt);
            }
        });
        getContentPane().add(btnkasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 410, 220));

        btnlaporan.setBorderPainted(false);
        btnlaporan.setContentAreaFilled(false);
        btnlaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlaporanActionPerformed(evt);
            }
        });
        getContentPane().add(btnlaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 460, 420, 220));

        ubahharga.setBorderPainted(false);
        ubahharga.setContentAreaFilled(false);
        ubahharga.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ubahharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahhargaActionPerformed(evt);
            }
        });
        getContentPane().add(ubahharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, 430, 220));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bgmenu.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ubahhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahhargaActionPerformed
        try {
            menu a = new menu();
            a.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(homeadmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ubahhargaActionPerformed

    private void btngrafikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrafikActionPerformed
        grafik a = new grafik();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btngrafikActionPerformed

    private void btnkasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkasirActionPerformed
        try {
            manajemenkasir a = new manajemenkasir();
            a.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(homeadmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnkasirActionPerformed

    private void btnlaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlaporanActionPerformed
       laporan a = new laporan();
       a.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnlaporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homeadmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btngrafik;
    private javax.swing.JButton btnkasir;
    private javax.swing.JButton btnlaporan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton ubahharga;
    // End of variables declaration//GEN-END:variables
}
