/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.File;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableCellRenderer;
import model.mlaporan;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author acer
 */
public class laporan extends javax.swing.JFrame {

    mlaporan laporan;
    JasperReport jasperReport3;
    JasperDesign jasperDesign3;
    JasperPrint jasperPrint3;
    Map<String, Object> param3 = new HashMap<String, Object>();
    public TableCellRenderer kanan = new RenderingKanan();

    public laporan() {
        try {
            this.laporan = new mlaporan();
            initComponents();
        } catch (SQLException ex) {
            Logger.getLogger(laporan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Creates new form laporan
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        tglakhir = new com.toedter.calendar.JDateChooser();
        tglawal = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panelminuman = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtminuman1 = new javax.swing.JLabel();
        txtminuman2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtmakanan6 = new javax.swing.JLabel();
        paneltoping = new javax.swing.JPanel();
        txttoping3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txttoping1 = new javax.swing.JLabel();
        txttoping2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        panelmakan = new javax.swing.JPanel();
        txtmakanan2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtmakanan1 = new javax.swing.JLabel();
        txtmakanan3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnmanajemenkasir = new javax.swing.JButton();
        btneditharga = new javax.swing.JButton();
        btnlaporan = new javax.swing.JButton();
        btngrafik = new javax.swing.JButton();
        printpdf = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txttotalpenjualan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 890, 590));
        getContentPane().add(tglakhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 140, 190, 40));
        getContentPane().add(tglawal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 90, 190, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Tanggal Akhir");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 140, 170, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Tanggal Awal");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 90, 170, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/set tanggal.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/set tanggal2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 190, 140, 60));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout admin.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout admin2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 20, 130, 60));

        panelminuman.setBackground(new java.awt.Color(255, 153, 0));
        panelminuman.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("minuman");
        panelminuman.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("1. ");
        panelminuman.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        txtminuman1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panelminuman.add(txtminuman1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 160, 20));

        txtminuman2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtminuman2.setText(" ");
        panelminuman.add(txtminuman2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 160, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("2. ");
        panelminuman.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("3. ");
        panelminuman.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtmakanan6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtmakanan6.setText(" ");
        panelminuman.add(txtmakanan6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 160, -1));

        getContentPane().add(panelminuman, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 300, 230, 200));

        paneltoping.setBackground(new java.awt.Color(255, 153, 0));
        paneltoping.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txttoping3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txttoping3.setText(" ");
        paneltoping.add(txttoping3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 110, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("topping");
        paneltoping.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("1. ");
        paneltoping.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        txttoping1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        paneltoping.add(txttoping1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 120, 20));

        txttoping2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txttoping2.setText(" ");
        paneltoping.add(txttoping2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 110, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("3. ");
        paneltoping.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("2. ");
        paneltoping.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        getContentPane().add(paneltoping, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 300, 180, 200));

        panelmakan.setBackground(new java.awt.Color(255, 153, 0));
        panelmakan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtmakanan2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtmakanan2.setText(" ");
        panelmakan.add(txtmakanan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 250, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("makanan");
        panelmakan.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("3. ");
        panelmakan.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("1. ");
        panelmakan.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("2. ");
        panelmakan.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        txtmakanan1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panelmakan.add(txtmakanan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 250, 20));

        txtmakanan3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtmakanan3.setText(" ");
        panelmakan.add(txtmakanan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 250, -1));

        getContentPane().add(panelmakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 520, 320, 200));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("produk terlaris");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 260, 410, -1));

        btnmanajemenkasir.setBorderPainted(false);
        btnmanajemenkasir.setContentAreaFilled(false);
        btnmanajemenkasir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmanajemenkasir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btnkasir.png"))); // NOI18N
        btnmanajemenkasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanajemenkasirActionPerformed(evt);
            }
        });
        getContentPane().add(btnmanajemenkasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 280, 60));

        btneditharga.setBorderPainted(false);
        btneditharga.setContentAreaFilled(false);
        btneditharga.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneditharga.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btnharga.png"))); // NOI18N
        btneditharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnedithargaActionPerformed(evt);
            }
        });
        getContentPane().add(btneditharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 170, 60));

        btnlaporan.setBorderPainted(false);
        btnlaporan.setContentAreaFilled(false);
        btnlaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlaporan.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btnlaporan.png"))); // NOI18N
        btnlaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlaporanActionPerformed(evt);
            }
        });
        getContentPane().add(btnlaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 20, 160, 60));

        btngrafik.setBorderPainted(false);
        btngrafik.setContentAreaFilled(false);
        btngrafik.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btngrafik.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btngrafik.png"))); // NOI18N
        btngrafik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrafikActionPerformed(evt);
            }
        });
        getContentPane().add(btngrafik, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 20, 110, 60));

        printpdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/print.png"))); // NOI18N
        printpdf.setBorderPainted(false);
        printpdf.setContentAreaFilled(false);
        printpdf.setFocusPainted(false);
        printpdf.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/print2.png"))); // NOI18N
        printpdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printpdfActionPerformed(evt);
            }
        });
        getContentPane().add(printpdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 190, 160, 60));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setText("total penjualan");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 689, -1, 60));

        txttotalpenjualan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(txttotalpenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 690, 280, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/laporan.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Date pertama = this.tglawal.getDate();
            Date kedua = this.tglakhir.getDate();
            String tglawal = gettanggal(pertama);
            String tglakhir = gettanggal(kedua);
            if (pertama.equals(kedua)) {
                table.setModel(laporan.getlaporan(tglawal, tglakhir));
                table.getColumnModel().getColumn(6).setCellRenderer(kanan);
                settop(tglawal, tglakhir);
                txttotalpenjualan.setText(laporan.gettotaluang(tglawal, tglakhir));
            } else if (pertama.before(kedua)) {
                table.setModel(laporan.getlaporan(tglawal, tglakhir));
                table.getColumnModel().getColumn(6).setCellRenderer(kanan);
                settop(tglawal, tglakhir);
                txttotalpenjualan.setText(laporan.gettotaluang(tglawal, tglakhir));

            } else {
                message("tgl awal harus tidak boleh melebihi tgl akhir");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public void settop(String tglawal, String tglakhir) {
        String datamakanan[] = laporan.gettopmakanan(tglawal, tglakhir);
        String datatoping[] = laporan.gettoptoping(tglawal, tglakhir);
        String dataminuman[] = laporan.gettopminum(tglawal, tglakhir);
        txtmakanan1.setText(datamakanan[0]);
        txtmakanan2.setText(datamakanan[1]);
        txtmakanan3.setText(datamakanan[2]);
        txtminuman1.setText(dataminuman[0]);
        txtminuman2.setText(dataminuman[1]);
        txtmakanan6.setText(dataminuman[2]);
        txttoping1.setText(datatoping[0]);
        txttoping2.setText(datatoping[1]);
        txttoping3.setText(datatoping[2]);
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            login a = new login();
            a.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(grafik.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnedithargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnedithargaActionPerformed
        try {
            menu a = new menu();
            a.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(laporan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnedithargaActionPerformed

    private void btnmanajemenkasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanajemenkasirActionPerformed
        try {
            manajemenkasir a = new manajemenkasir();
            a.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(laporan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnmanajemenkasirActionPerformed

    private void btngrafikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrafikActionPerformed
        grafik a = new grafik();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btngrafikActionPerformed

    private void btnlaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlaporanActionPerformed
        laporan a = new laporan();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnlaporanActionPerformed

    private void printpdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printpdfActionPerformed
        try {
            Date pertama = this.tglawal.getDate();
            Date kedua = this.tglakhir.getDate();
            String tglawal = gettanggal(pertama);
            String tglakhir = gettanggal(kedua);
            File file3 = new File("src/report/laporanpdf.jrxml");
            System.out.println("masukminuman");
            jasperDesign3 = JRXmlLoader.load(file3);
            param3.clear();
            param3.put("tglawal", tglawal);
            param3.put("tglakhir", tglakhir);
            jasperReport3 = JasperCompileManager.compileReport(jasperDesign3);
            jasperPrint3 = JasperFillManager.fillReport(jasperReport3, param3, laporan.getConnection());
            JasperViewer.viewReport(jasperPrint3, true);
//JasperPrintManager.printReport(jasperPrint3, false);
        } catch (JRException ex) {
            Logger.getLogger(laporan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printpdfActionPerformed
    public String gettanggal(Date date) {
        DateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
        return dateformat.format(date);
    }

    public void message(String txt) {
        JOptionPane.showMessageDialog(null, txt, "error", JOptionPane.OK_OPTION);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneditharga;
    private javax.swing.JButton btngrafik;
    private javax.swing.JButton btnlaporan;
    private javax.swing.JButton btnmanajemenkasir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelmakan;
    private javax.swing.JPanel panelminuman;
    private javax.swing.JPanel paneltoping;
    private javax.swing.JButton printpdf;
    private javax.swing.JTable table;
    private com.toedter.calendar.JDateChooser tglakhir;
    private com.toedter.calendar.JDateChooser tglawal;
    private javax.swing.JLabel txtmakanan1;
    private javax.swing.JLabel txtmakanan2;
    private javax.swing.JLabel txtmakanan3;
    private javax.swing.JLabel txtmakanan6;
    private javax.swing.JLabel txtminuman1;
    private javax.swing.JLabel txtminuman2;
    private javax.swing.JLabel txttoping1;
    private javax.swing.JLabel txttoping2;
    private javax.swing.JLabel txttoping3;
    private javax.swing.JLabel txttotalpenjualan;
    // End of variables declaration//GEN-END:variables
}
