/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.mkasir;

/**
 *
 * @author acer
 */
public class manajemenkasir extends javax.swing.JFrame {

    /**
     * Creates new form manajemenkasir
     */
    mkasir kasir;
    String id;
    String status = "";

    public manajemenkasir() throws SQLException {
        initComponents();
        kasir = new mkasir();
        table.setModel(kasir.getkasir());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JTextField();
        txtusername = new javax.swing.JTextField();
        btnhapus = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btngrafik = new javax.swing.JButton();
        btnmanajemenkasir = new javax.swing.JButton();
        btneditharga = new javax.swing.JButton();
        btnlaporan = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(822, 80, 500, 640));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("username");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        txtpassword.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtpassword.setToolTipText("");
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 410, 90));

        txtusername.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtusername.setToolTipText("");
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 410, 90));

        btnhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hapus.png"))); // NOI18N
        btnhapus.setBorderPainted(false);
        btnhapus.setContentAreaFilled(false);
        btnhapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnhapus.setFocusPainted(false);
        btnhapus.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hapus2.png"))); // NOI18N
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 150, 70));

        btnsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/simpan.png"))); // NOI18N
        btnsimpan.setBorderPainted(false);
        btnsimpan.setContentAreaFilled(false);
        btnsimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsimpan.setFocusPainted(false);
        btnsimpan.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/simpan2.png"))); // NOI18N
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 150, 70));

        btngrafik.setBorderPainted(false);
        btngrafik.setContentAreaFilled(false);
        btngrafik.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btngrafik.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btngrafik.png"))); // NOI18N
        btngrafik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrafikActionPerformed(evt);
            }
        });
        getContentPane().add(btngrafik, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 20, 130, 60));

        btnmanajemenkasir.setBorderPainted(false);
        btnmanajemenkasir.setContentAreaFilled(false);
        btnmanajemenkasir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmanajemenkasir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btnkasir.png"))); // NOI18N
        btnmanajemenkasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanajemenkasirActionPerformed(evt);
            }
        });
        getContentPane().add(btnmanajemenkasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 280, 60));

        btneditharga.setBorderPainted(false);
        btneditharga.setContentAreaFilled(false);
        btneditharga.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneditharga.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btnharga.png"))); // NOI18N
        btneditharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnedithargaActionPerformed(evt);
            }
        });
        getContentPane().add(btneditharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 190, 60));

        btnlaporan.setBorderPainted(false);
        btnlaporan.setContentAreaFilled(false);
        btnlaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlaporan.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btnlaporan.png"))); // NOI18N
        btnlaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlaporanActionPerformed(evt);
            }
        });
        getContentPane().add(btnlaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 20, 160, 60));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout admin.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout admin2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 140, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kasir.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        id = table.getValueAt(table.getSelectedRow(), 0).toString();
        String nama = table.getValueAt(table.getSelectedRow(), 1).toString();
        String password = table.getValueAt(table.getSelectedRow(), 2).toString();
        txtpassword.setText(password);
        txtusername.setText(nama);
        status = "update";
        btnsimpan.setText("update");
    }//GEN-LAST:event_tableMouseClicked

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        try {
            if (status.equalsIgnoreCase("update")) {
                kasir.updatekasir(txtusername.getText(), txtpassword.getText(), id);
                txtpassword.setText("");
                txtusername.setText("");
                status = "simpan";
                table.setModel(kasir.getkasir());
                btnsimpan.setText("simpan");
            } else {
                kasir.insertkasir(txtusername.getText(), txtpassword.getText());
                txtpassword.setText("");
                txtusername.setText("");
                table.setModel(kasir.getkasir());
            }
        } catch (SQLException ex) {
            Logger.getLogger(manajemenkasir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        try {
            txtpassword.setText("");
            txtusername.setText("");
            kasir.deletekasir((String) table.getValueAt(table.getSelectedRow(), 0));
            table.setModel(kasir.getkasir());
            status = "simpan";
        } catch (SQLException ex) {
            Logger.getLogger(manajemenkasir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnedithargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnedithargaActionPerformed
        try {
            menu a = new menu();
            a.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(laporan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnedithargaActionPerformed

    private void btnmanajemenkasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanajemenkasirActionPerformed
        try {
            manajemenkasir a = new manajemenkasir();
            a.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(laporan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnmanajemenkasirActionPerformed

    private void btngrafikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrafikActionPerformed
        grafik a= new grafik();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btngrafikActionPerformed

    private void btnlaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlaporanActionPerformed
        laporan a = new laporan();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnlaporanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            login a = new login();
            a.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(grafik.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manajemenkasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manajemenkasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manajemenkasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manajemenkasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new manajemenkasir().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(manajemenkasir.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneditharga;
    private javax.swing.JButton btngrafik;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnlaporan;
    private javax.swing.JButton btnmanajemenkasir;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
