/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author Nila
 */
public class pesanan extends javax.swing.JFrame {

    /**
     * Creates new form pesanan
     */
    double hargatotal = 0;
    double hargasatu = 0;

    public pesanan() {
        initComponents();
        showtgl();
        showjam();
    }

    public void showtgl() {
        Date d = new Date();
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        boxtgl.setText(df.format(d));
    }

    public void showjam() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat df = new SimpleDateFormat("hh:mm:ss a");
                boxjam.setText(df.format(d));
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupmenu = new javax.swing.ButtonGroup();
        panelmenu = new javax.swing.JPanel();
        seblak_original = new javax.swing.JRadioButton();
        seblakmi = new javax.swing.JRadioButton();
        mi_goreng = new javax.swing.JRadioButton();
        seblak_bakso = new javax.swing.JRadioButton();
        pillevel = new javax.swing.JComboBox<>();
        paneltoping = new javax.swing.JPanel();
        pil1 = new javax.swing.JCheckBox();
        pil2 = new javax.swing.JCheckBox();
        pil3 = new javax.swing.JCheckBox();
        pil4 = new javax.swing.JCheckBox();
        pil5 = new javax.swing.JCheckBox();
        pil6 = new javax.swing.JCheckBox();
        pil7 = new javax.swing.JCheckBox();
        pil8 = new javax.swing.JCheckBox();
        pil13 = new javax.swing.JCheckBox();
        pil14 = new javax.swing.JCheckBox();
        pil15 = new javax.swing.JCheckBox();
        pil16 = new javax.swing.JCheckBox();
        pil12 = new javax.swing.JCheckBox();
        pil11 = new javax.swing.JCheckBox();
        pil10 = new javax.swing.JCheckBox();
        pil9 = new javax.swing.JCheckBox();
        tambah = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        boxpesanan = new javax.swing.JTextArea();
        jButton12 = new javax.swing.JButton();
        boxhargatotal = new javax.swing.JTextField();
        boxtgl = new javax.swing.JTextField();
        boxjam = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelmenu.setBackground(new java.awt.Color(255, 153, 51));
        panelmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        groupmenu.add(seblak_original);
        seblak_original.setText("seblak original 7k");
        seblak_original.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seblak_originalActionPerformed(evt);
            }
        });
        panelmenu.add(seblak_original, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        groupmenu.add(seblakmi);
        seblakmi.setText("seblakmi 10k");
        seblakmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seblakmiActionPerformed(evt);
            }
        });
        panelmenu.add(seblakmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        groupmenu.add(mi_goreng);
        mi_goreng.setText("mi goreng 12k");
        mi_goreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_gorengActionPerformed(evt);
            }
        });
        panelmenu.add(mi_goreng, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        groupmenu.add(seblak_bakso);
        seblak_bakso.setText("seblak bakso 20k");
        seblak_bakso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seblak_baksoActionPerformed(evt);
            }
        });
        panelmenu.add(seblak_bakso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        pillevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "level 1", "level 2", "level 3", "level 4", "level 5" }));
        panelmenu.add(pillevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        getContentPane().add(panelmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 297, 187));

        paneltoping.setBackground(new java.awt.Color(255, 153, 51));
        paneltoping.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pil1.setText("susu");
        paneltoping.add(pil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 27, -1, -1));

        pil2.setText("bakso");
        paneltoping.add(pil2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 68, -1, -1));

        pil3.setText("makaroni");
        paneltoping.add(pil3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 109, -1, -1));

        pil4.setText("spageti");
        paneltoping.add(pil4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 150, -1, -1));

        pil5.setText("mi");
        paneltoping.add(pil5, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 27, -1, -1));

        pil6.setText("cilot");
        paneltoping.add(pil6, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 68, -1, -1));

        pil7.setText("krupuk");
        paneltoping.add(pil7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 109, -1, -1));

        pil8.setText("ceker");
        paneltoping.add(pil8, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 150, -1, -1));

        pil13.setText("somay");
        paneltoping.add(pil13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        pil14.setText("jeroan");
        paneltoping.add(pil14, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 68, -1, -1));

        pil15.setText("kerang");
        paneltoping.add(pil15, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 109, -1, -1));

        pil16.setText("gurita");
        paneltoping.add(pil16, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 150, -1, -1));

        pil12.setText("cumi");
        paneltoping.add(pil12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        pil11.setText("ikan");
        paneltoping.add(pil11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        pil10.setText("daging");
        paneltoping.add(pil10, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 68, -1, -1));

        pil9.setText("tulang");
        paneltoping.add(pil9, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 27, -1, -1));

        getContentPane().add(paneltoping, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 320, 190));

        tambah.setText("tambah");
        tambah.setEnabled(false);
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 80, 60));

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("minuman 10");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 90, 70));

        jButton3.setText("minuman 1");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 70));

        jButton4.setText("minuman 2");
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, 70));

        jButton5.setText("minuman 3");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 90, 70));

        jButton6.setText("minuman 4");
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 90, 70));

        jButton7.setText("miuman 5");
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 90, 70));

        jButton8.setText("minuman 6");
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 90, 70));

        jButton9.setText("minuman 7");
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 90, 70));

        jButton10.setText("minuman 8");
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 90, 70));

        jButton11.setText("minuman 9");
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 90, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, 560, 200));

        jPanel2.setBackground(new java.awt.Color(51, 255, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 420, 560, 280));

        jPanel3.setBackground(new java.awt.Color(51, 255, 51));

        boxpesanan.setEditable(false);
        boxpesanan.setColumns(20);
        boxpesanan.setRows(5);
        jScrollPane1.setViewportView(boxpesanan);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 740, 230));

        jButton12.setText("bayar");
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 680, 130, 60));

        boxhargatotal.setEditable(false);
        boxhargatotal.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        boxhargatotal.setForeground(new java.awt.Color(255, 51, 0));
        boxhargatotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        boxhargatotal.setText("harga nya");
        boxhargatotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxhargatotalActionPerformed(evt);
            }
        });
        getContentPane().add(boxhargatotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 80, 350, 50));

        boxtgl.setEditable(false);
        boxtgl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        boxtgl.setText("jam nya");
        getContentPane().add(boxtgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 110, 30));

        boxjam.setEditable(false);
        boxjam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        boxjam.setText("jam nya");
        getContentPane().add(boxjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, 30));

        jButton13.setText("clear");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 90, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        if (seblak_original.isSelected()) {
            hargasatu = hargasatu + 7000;
            boxpesanan.append("seblak original");
        } else if (seblakmi.isSelected()) {
            hargasatu = hargasatu + 10000;
            boxpesanan.append("seblak mi");
        } else if (mi_goreng.isSelected()) {
            hargasatu = hargasatu + 12000;
            boxpesanan.append("mi goreng");
        } else if (seblak_bakso.isSelected()) {
            hargasatu = hargasatu + 20000;
            boxpesanan.append("seblak bakso");
        }
        String level = pillevel.getSelectedItem().toString();
        boxpesanan.append(" = " + level);
        boxpesanan.append("\n Topping : \n");
        if (pil1.isSelected()) {
            hargasatu = hargasatu + 2000;
            boxpesanan.append("susu ");
        }
        if (pil2.isSelected()) {
            hargasatu = hargasatu + 2000;
            boxpesanan.append("bakso ");
        }
        if (pil3.isSelected()) {
            hargasatu = hargasatu + 2000;
            boxpesanan.append("makaroni ");
        }
        if (pil4.isSelected()) {
            hargasatu = hargasatu + 2000;
            boxpesanan.append("spageti ");
        }
        if (pil5.isSelected()) {
            hargasatu = hargasatu + 2000;
            boxpesanan.append("mi ");
        }
        if (pil6.isSelected()) {
            hargasatu = hargasatu + 2000;
            boxpesanan.append("cilot ");
        }
        if (pil7.isSelected()) {
            hargasatu = hargasatu + 2000;
            boxpesanan.append("krupuk ");
        }
        if (pil8.isSelected()) {
            hargasatu = hargasatu + 2000;
            boxpesanan.append("ceker ");
        }
        if (pil9.isSelected()) {
            hargasatu = hargasatu + 2000;
            boxpesanan.append("tulang ");
        }
        if (pil10.isSelected()) {
            hargasatu = hargasatu + 2000;
            boxpesanan.append("daging ");
        }
        if (pil11.isSelected()) {
            hargasatu = hargasatu + 2000;
            boxpesanan.append("ikan ");
        }
        if (pil12.isSelected()) {
            hargasatu = hargasatu + 2000;
            boxpesanan.append("cumi ");
        }
        if (pil13.isSelected()) {
            hargasatu = hargasatu + 2000;
            boxpesanan.append("siomay ");
        }
        if (pil14.isSelected()) {
            hargasatu = hargasatu + 2000;
            boxpesanan.append("jeroan ");
        }
        if (pil15.isSelected()) {
            hargasatu = hargasatu + 2000;
            boxpesanan.append("kerang ");
        }
        if (pil16.isSelected()) {
            hargasatu = hargasatu + 2000;
            boxpesanan.append("gurita ");
        }
        boxpesanan.append("\t : " + hargasatu);
        boxpesanan.append("\n");
        hargatotal = hargatotal + hargasatu;
        hargasatu = 0;
        boxhargatotal.setText("" + hargatotal);
        clear();
    }//GEN-LAST:event_tambahActionPerformed
    public void clear() {
        tambah.setEnabled(false);
        groupmenu.clearSelection();
        pil1.setSelected(false);
        pil2.setSelected(false);
        pil3.setSelected(false);
        pil4.setSelected(false);
        pil5.setSelected(false);
        pil6.setSelected(false);
        pil7.setSelected(false);
        pil8.setSelected(false);
        pil9.setSelected(false);
        pil10.setSelected(false);
        pil11.setSelected(false);
        pil12.setSelected(false);
        pil13.setSelected(false);
        pil14.setSelected(false);
        pil15.setSelected(false);
        pil16.setSelected(false);
        pillevel.setSelectedIndex(0);
    }
    private void boxhargatotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxhargatotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxhargatotalActionPerformed

    private void seblakmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seblakmiActionPerformed
       tambah.setEnabled(true);
    }//GEN-LAST:event_seblakmiActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        boxpesanan.setText("");
        boxhargatotal.setText("");
        hargatotal=0;
        clear();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void seblak_originalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seblak_originalActionPerformed
        tambah.setEnabled(true);
    }//GEN-LAST:event_seblak_originalActionPerformed

    private void mi_gorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_gorengActionPerformed
      tambah.setEnabled(true);
    }//GEN-LAST:event_mi_gorengActionPerformed

    private void seblak_baksoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seblak_baksoActionPerformed
      tambah.setEnabled(true);
    }//GEN-LAST:event_seblak_baksoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField boxhargatotal;
    private javax.swing.JTextField boxjam;
    private javax.swing.JTextArea boxpesanan;
    private javax.swing.JTextField boxtgl;
    private javax.swing.ButtonGroup groupmenu;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton mi_goreng;
    private javax.swing.JPanel panelmenu;
    private javax.swing.JPanel paneltoping;
    private javax.swing.JCheckBox pil1;
    private javax.swing.JCheckBox pil10;
    private javax.swing.JCheckBox pil11;
    private javax.swing.JCheckBox pil12;
    private javax.swing.JCheckBox pil13;
    private javax.swing.JCheckBox pil14;
    private javax.swing.JCheckBox pil15;
    private javax.swing.JCheckBox pil16;
    private javax.swing.JCheckBox pil2;
    private javax.swing.JCheckBox pil3;
    private javax.swing.JCheckBox pil4;
    private javax.swing.JCheckBox pil5;
    private javax.swing.JCheckBox pil6;
    private javax.swing.JCheckBox pil7;
    private javax.swing.JCheckBox pil8;
    private javax.swing.JCheckBox pil9;
    private javax.swing.JComboBox<String> pillevel;
    private javax.swing.JRadioButton seblak_bakso;
    private javax.swing.JRadioButton seblak_original;
    private javax.swing.JRadioButton seblakmi;
    private javax.swing.JButton tambah;
    // End of variables declaration//GEN-END:variables
}
