/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import model.mpesanan;

/**
 *
 * @author Nila
 */
public class pesananflow extends javax.swing.JFrame {

    /**
     * Creates new form pesanan
     */
    mpesanan pesanan;
    double hargatotal = 0;
    double hargasatu = 0;
    String idpesanan = null;
    String idtoping = null;
    int level;
    boolean toping = false;

    public pesananflow() throws SQLException {
        initComponents();
        showtgl();
        showjam();
        pesanan = new mpesanan();
        idpesanan = pesanan.getidpesanan();
    }

    public void showtgl() {
        Date d = new Date();
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        boxtgl.setText(df.format(d));
    }

    public void showjam() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat df = new SimpleDateFormat("hh:mm:ss a");
                boxjam.setText(df.format(d));
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupmenu = new javax.swing.ButtonGroup();
        panelmenu = new javax.swing.JPanel();
        seblak_original = new javax.swing.JRadioButton();
        seblakmi = new javax.swing.JRadioButton();
        mi_goreng = new javax.swing.JRadioButton();
        seblak_bakso = new javax.swing.JRadioButton();
        pillevel = new javax.swing.JComboBox<>();
        paneltoping = new javax.swing.JPanel();
        pil1 = new javax.swing.JCheckBox();
        pil2 = new javax.swing.JCheckBox();
        pil3 = new javax.swing.JCheckBox();
        pil4 = new javax.swing.JCheckBox();
        pil5 = new javax.swing.JCheckBox();
        pil6 = new javax.swing.JCheckBox();
        pil7 = new javax.swing.JCheckBox();
        pil8 = new javax.swing.JCheckBox();
        pil13 = new javax.swing.JCheckBox();
        pil14 = new javax.swing.JCheckBox();
        pil15 = new javax.swing.JCheckBox();
        pil16 = new javax.swing.JCheckBox();
        pil12 = new javax.swing.JCheckBox();
        pil11 = new javax.swing.JCheckBox();
        pil10 = new javax.swing.JCheckBox();
        pil9 = new javax.swing.JCheckBox();
        tambah = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        minuman1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        panelpesanan = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablemenu = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabeltoping = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableminuman = new javax.swing.JTable();
        btnbayar = new javax.swing.JButton();
        boxhargatotal = new javax.swing.JTextField();
        boxtgl = new javax.swing.JTextField();
        boxjam = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        btndeleteminuman = new javax.swing.JButton();
        btndeletemenu = new javax.swing.JButton();
        btndeletetoping = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelmenu.setBackground(new java.awt.Color(255, 153, 51));
        panelmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        groupmenu.add(seblak_original);
        seblak_original.setText("seblak original 7k");
        seblak_original.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seblak_originalActionPerformed(evt);
            }
        });
        panelmenu.add(seblak_original, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        groupmenu.add(seblakmi);
        seblakmi.setText("seblakmi 10k");
        seblakmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seblakmiActionPerformed(evt);
            }
        });
        panelmenu.add(seblakmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        groupmenu.add(mi_goreng);
        mi_goreng.setText("mi goreng 12k");
        mi_goreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_gorengActionPerformed(evt);
            }
        });
        panelmenu.add(mi_goreng, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        groupmenu.add(seblak_bakso);
        seblak_bakso.setText("seblak bakso 20k");
        seblak_bakso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seblak_baksoActionPerformed(evt);
            }
        });
        panelmenu.add(seblak_bakso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        pillevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "level 1", "level 2", "level 3", "level 4", "level 5" }));
        panelmenu.add(pillevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        getContentPane().add(panelmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 297, 187));

        paneltoping.setBackground(new java.awt.Color(255, 153, 51));
        paneltoping.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pil1.setText("susu");
        paneltoping.add(pil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 27, -1, -1));

        pil2.setText("bakso");
        paneltoping.add(pil2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 68, -1, -1));

        pil3.setText("makaroni");
        paneltoping.add(pil3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 109, -1, -1));

        pil4.setText("spageti");
        paneltoping.add(pil4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 150, -1, -1));

        pil5.setText("mi");
        paneltoping.add(pil5, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 27, -1, -1));

        pil6.setText("cilot");
        paneltoping.add(pil6, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 68, -1, -1));

        pil7.setText("krupuk");
        paneltoping.add(pil7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 109, -1, -1));

        pil8.setText("ceker");
        paneltoping.add(pil8, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 150, -1, -1));

        pil13.setText("somay");
        paneltoping.add(pil13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        pil14.setText("jeroan");
        paneltoping.add(pil14, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 68, -1, -1));

        pil15.setText("kerang");
        paneltoping.add(pil15, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 109, -1, -1));

        pil16.setText("gurita");
        paneltoping.add(pil16, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 150, -1, -1));

        pil12.setText("cumi");
        paneltoping.add(pil12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        pil11.setText("ikan");
        paneltoping.add(pil11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        pil10.setText("daging");
        paneltoping.add(pil10, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 68, -1, -1));

        pil9.setText("tulang");
        paneltoping.add(pil9, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 27, -1, -1));

        getContentPane().add(paneltoping, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 320, 190));

        tambah.setText("tambah");
        tambah.setEnabled(false);
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 80, 60));

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("minuman 10");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 90, 70));

        minuman1.setText("minuman 1");
        minuman1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minuman1ActionPerformed(evt);
            }
        });
        jPanel1.add(minuman1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 70));

        jButton4.setText("minuman 2");
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, 70));

        jButton5.setText("minuman 3");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 90, 70));

        jButton6.setText("minuman 4");
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 90, 70));

        jButton7.setText("miuman 5");
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 90, 70));

        jButton8.setText("minuman 6");
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 90, 70));

        jButton9.setText("minuman 7");
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 90, 70));

        jButton10.setText("minuman 8");
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 90, 70));

        jButton11.setText("minuman 9");
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 90, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, 560, 200));

        panelpesanan.setBackground(new java.awt.Color(51, 255, 51));
        panelpesanan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablemenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id_pesan", "nama_menu", "level"
            }
        ));
        tablemenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablemenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablemenu);
        if (tablemenu.getColumnModel().getColumnCount() > 0) {
            tablemenu.getColumnModel().getColumn(0).setMinWidth(70);
            tablemenu.getColumnModel().getColumn(0).setMaxWidth(20);
            tablemenu.getColumnModel().getColumn(2).setMinWidth(50);
            tablemenu.getColumnModel().getColumn(2).setMaxWidth(50);
        }

        panelpesanan.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 370, 250));

        tabeltoping.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id_pesan_toping", "nama_toping"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabeltoping);

        panelpesanan.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 190, 250));

        tableminuman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id_pesan", "nama_minuman"
            }
        ));
        jScrollPane3.setViewportView(tableminuman);

        panelpesanan.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 240, 250));

        getContentPane().add(panelpesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 1300, 250));

        btnbayar.setText("bayar");
        btnbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbayarActionPerformed(evt);
            }
        });
        getContentPane().add(btnbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 680, 130, 60));

        boxhargatotal.setEditable(false);
        boxhargatotal.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        boxhargatotal.setForeground(new java.awt.Color(255, 51, 0));
        boxhargatotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        boxhargatotal.setText("harga nya");
        boxhargatotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxhargatotalActionPerformed(evt);
            }
        });
        getContentPane().add(boxhargatotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 80, 350, 50));

        boxtgl.setEditable(false);
        boxtgl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        boxtgl.setText("jam nya");
        getContentPane().add(boxtgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 110, 30));

        boxjam.setEditable(false);
        boxjam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        boxjam.setText("jam nya");
        getContentPane().add(boxjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, 30));

        clear.setText("clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 90, 60));

        btndeleteminuman.setText("delete minuman");
        btndeleteminuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteminumanActionPerformed(evt);
            }
        });
        getContentPane().add(btndeleteminuman, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 350, 130, 60));

        btndeletemenu.setText("delete menu");
        btndeletemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletemenuActionPerformed(evt);
            }
        });
        getContentPane().add(btndeletemenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 100, 60));

        btndeletetoping.setText("delete toping");
        btndeletetoping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletetopingActionPerformed(evt);
            }
        });
        getContentPane().add(btndeletetoping, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 100, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        ArrayList<String> daftartoping = new ArrayList<String>();
        level = pillevel.getSelectedIndex() + 1;
        int menu = 0;
        if (seblak_original.isSelected()) {
            hargasatu = hargasatu + 7000;
            menu = 1;
        } else if (seblakmi.isSelected()) {
            hargasatu = hargasatu + 10000;
            menu = 2;
        } else if (mi_goreng.isSelected()) {
            hargasatu = hargasatu + 12000;
            menu = 3;
        } else if (seblak_bakso.isSelected()) {
            hargasatu = hargasatu + 20000;
            menu = 4;
        }

        if (pil1.isSelected()) {
            hargasatu = hargasatu + 2000;
            toping = true;
            daftartoping.add("1");
        }
        if (pil2.isSelected()) {
            hargasatu = hargasatu + 2000;
            toping = true;
            daftartoping.add("2");
        }
        if (pil3.isSelected()) {
            hargasatu = hargasatu + 2000;
            toping = true;
            daftartoping.add("3");
        }
        if (pil4.isSelected()) {
            hargasatu = hargasatu + 2000;
            toping = true;
            daftartoping.add("4");
        }
        if (pil5.isSelected()) {
            hargasatu = hargasatu + 2000;
            toping = true;
            daftartoping.add("5");
        }
        if (pil6.isSelected()) {
            hargasatu = hargasatu + 2000;
            toping = true;
            daftartoping.add("6");
        }
        if (pil7.isSelected()) {
            hargasatu = hargasatu + 2000;
            toping = true;
            daftartoping.add("7");
        }
        if (pil8.isSelected()) {
            hargasatu = hargasatu + 2000;
            toping = true;
            daftartoping.add("8");
        }
        if (pil9.isSelected()) {
            hargasatu = hargasatu + 2000;
            toping = true;
            daftartoping.add("9");
        }
        if (pil10.isSelected()) {
            hargasatu = hargasatu + 2000;
            toping = true;
            daftartoping.add("10");
        }
        if (pil11.isSelected()) {
            hargasatu = hargasatu + 2000;
            toping = true;
            daftartoping.add("11");
        }
        if (pil12.isSelected()) {
            hargasatu = hargasatu + 2000;
            toping = true;
            daftartoping.add("12");
        }
        if (pil13.isSelected()) {
            hargasatu = hargasatu + 2000;
            toping = true;
            daftartoping.add("13");
        }
        if (pil14.isSelected()) {
            hargasatu = hargasatu + 2000;
            toping = true;
            daftartoping.add("14");
        }
        if (pil15.isSelected()) {
            hargasatu = hargasatu + 2000;
            toping = true;
            daftartoping.add("15");
        }
        if (pil16.isSelected()) {
            hargasatu = hargasatu + 2000;
            toping = true;
            daftartoping.add("16");
        }

        System.out.println("idtoping sesudah" + idtoping);
        inserttoping(daftartoping);
        insertmenu("" + menu);
        idtoping = null;
        hargatotal = hargatotal + hargasatu;
        hargasatu = 0;
        boxhargatotal.setText("" + hargatotal);
        refreshtable();
        clear();
    }//GEN-LAST:event_tambahActionPerformed
    public void insertmenu(String id) {
        //data[0]=id_pesanan
        //data[1]=id_menu
        //data[2]=id_toping
        //data[3]=level
        //data[4]=harga_bayar
        String data[] = {"" + idpesanan, id, idtoping, "" + level, "" + hargasatu};
        if (pesanan.tambahpesananmakan(data)) {
            message("berhasil insert makanan");
        } else {
            message("gagal insert makanan");
        }
    }

    public void inserttoping(ArrayList id) {
        //data[0]=id_pesan_toping
        //data[1]=id_toping
//        System.out.println("idtoping sebelum"+idtoping);
//        if (toping==true) {
//            idtoping = pesanan.getidtoping();
//            toping=false;
//        } else {
//            idtoping = null;
//        }
//        String data[] = {"" + idpesanan, id, idtoping};
//        if (pesanan.tambahtoping(data)) {
//            message("berhasil insert toping");
//        } else {
//            message("gagal insert toping");
//        }
        if (toping) {
            idtoping = pesanan.getidtoping();
            for (int i = 0; i < id.size(); i++) {
                if (pesanan.tambahtoping(idtoping, id.get(i).toString())) {
                    message("berhasil insert toping");
                } else {
                    message("gagal insert toping");
                }

            }
        }
        else{
            message("beli tanpa toping");
        }
    }

    public void clear() {
        tambah.setEnabled(false);
        groupmenu.clearSelection();
        pil1.setSelected(false);
        pil2.setSelected(false);
        pil3.setSelected(false);
        pil4.setSelected(false);
        pil5.setSelected(false);
        pil6.setSelected(false);
        pil7.setSelected(false);
        pil8.setSelected(false);
        pil9.setSelected(false);
        pil10.setSelected(false);
        pil11.setSelected(false);
        pil12.setSelected(false);
        pil13.setSelected(false);
        pil14.setSelected(false);
        pil15.setSelected(false);
        pil16.setSelected(false);
        pillevel.setSelectedIndex(0);
    }
    private void boxhargatotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxhargatotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxhargatotalActionPerformed

    private void seblakmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seblakmiActionPerformed
        tambah.setEnabled(true);
    }//GEN-LAST:event_seblakmiActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        panelpesanan.removeAll();
        panelpesanan.revalidate();
        panelpesanan.repaint();
        boxhargatotal.setText("");
        hargatotal = 0;
        clear();
    }//GEN-LAST:event_clearActionPerformed

    private void seblak_originalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seblak_originalActionPerformed
        tambah.setEnabled(true);
    }//GEN-LAST:event_seblak_originalActionPerformed

    private void mi_gorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_gorengActionPerformed
        tambah.setEnabled(true);
    }//GEN-LAST:event_mi_gorengActionPerformed

    private void seblak_baksoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seblak_baksoActionPerformed
        tambah.setEnabled(true);
    }//GEN-LAST:event_seblak_baksoActionPerformed

    private void minuman1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minuman1ActionPerformed
        String data[] = {idpesanan, "1", "10000"};
        pesanan.tambahpesananminum(data);
        refreshtable();
    }//GEN-LAST:event_minuman1ActionPerformed

    private void tablemenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablemenuMouseClicked
        try {
            String idtoping = tablemenu.getValueAt(tablemenu.getSelectedRow(), 3).toString();
            tabeltoping.setModel(pesanan.gettoping(idtoping));
        } catch (SQLException ex) {
            Logger.getLogger(pesananflow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tablemenuMouseClicked

    private void btndeleteminumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteminumanActionPerformed
        String idminuman = tableminuman.getValueAt(tableminuman.getSelectedRow(), 0).toString();
        if (pesanan.delete(idminuman)) {
            message("minuman di hapus");
        } else {
            message("gagal hapus");
        }
        refreshtable();
    }//GEN-LAST:event_btndeleteminumanActionPerformed

    private void btndeletetopingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletetopingActionPerformed
        String idtoping = tabeltoping.getValueAt(tabeltoping.getSelectedRow(), 0).toString();
        if (pesanan.deletetoping(idtoping)) {
            message("toping di hapus");
        } else {
            message("gagal hapus");
        }
        refreshtable();
    }//GEN-LAST:event_btndeletetopingActionPerformed

    private void btndeletemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletemenuActionPerformed
        String idmenu = tablemenu.getValueAt(tablemenu.getSelectedRow(), 0).toString();
        if (pesanan.delete(idmenu)) {
            message("menu di hapus");
        } else {
            message("gagal hapus");
        }
        refreshtable();
    }//GEN-LAST:event_btndeletemenuActionPerformed

    private void btnbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbayarActionPerformed
        idpesanan = pesanan.getidpesanan();
        tabeltoping.setModel(null);
        tablemenu.setModel(null);
        tableminuman.setModel(null);
    }//GEN-LAST:event_btnbayarActionPerformed

    public void refreshtable() {
        try {
            System.out.println("dapat id pesana" + idpesanan);
            tablemenu.setModel(pesanan.cekpesananmakanan(idpesanan));
            tableminuman.setModel(pesanan.cekpesananminuman(idpesanan));
            tabeltoping.setModel(pesanan.gettoping(idtoping));
        } catch (SQLException ex) {
            Logger.getLogger(pesananflow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void message(String txt) {
        JOptionPane.showMessageDialog(null, txt, "error", JOptionPane.OK_OPTION);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pesananflow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pesananflow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pesananflow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pesananflow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new pesananflow().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(pesananflow.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField boxhargatotal;
    private javax.swing.JTextField boxjam;
    private javax.swing.JTextField boxtgl;
    private javax.swing.JButton btnbayar;
    private javax.swing.JButton btndeletemenu;
    private javax.swing.JButton btndeleteminuman;
    private javax.swing.JButton btndeletetoping;
    private javax.swing.JButton clear;
    private javax.swing.ButtonGroup groupmenu;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton mi_goreng;
    private javax.swing.JButton minuman1;
    private javax.swing.JPanel panelmenu;
    private javax.swing.JPanel panelpesanan;
    private javax.swing.JPanel paneltoping;
    private javax.swing.JCheckBox pil1;
    private javax.swing.JCheckBox pil10;
    private javax.swing.JCheckBox pil11;
    private javax.swing.JCheckBox pil12;
    private javax.swing.JCheckBox pil13;
    private javax.swing.JCheckBox pil14;
    private javax.swing.JCheckBox pil15;
    private javax.swing.JCheckBox pil16;
    private javax.swing.JCheckBox pil2;
    private javax.swing.JCheckBox pil3;
    private javax.swing.JCheckBox pil4;
    private javax.swing.JCheckBox pil5;
    private javax.swing.JCheckBox pil6;
    private javax.swing.JCheckBox pil7;
    private javax.swing.JCheckBox pil8;
    private javax.swing.JCheckBox pil9;
    private javax.swing.JComboBox<String> pillevel;
    private javax.swing.JRadioButton seblak_bakso;
    private javax.swing.JRadioButton seblak_original;
    private javax.swing.JRadioButton seblakmi;
    private javax.swing.JTable tabeltoping;
    private javax.swing.JTable tablemenu;
    private javax.swing.JTable tableminuman;
    private javax.swing.JButton tambah;
    // End of variables declaration//GEN-END:variables
}
