/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import model.mpesanan;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Nila
 */
public class pesananflow extends javax.swing.JFrame {

    /**
     * Creates new form pesanan
     */
    mpesanan pesanan;
    double hargatotal = 0;
    double hargasatu = 0;
    String idpesanan = null;
    String idtoping = null;
    int level;
    boolean toping = false;
    popupkembalian popupkembalian = new popupkembalian();
    JasperReport jasperReport;
    JasperDesign jasperDesign;
    JasperPrint jasperPrint;
    Map<String, Object> param = new HashMap<String, Object>();

    public pesananflow() throws SQLException {
        initComponents();
        showtgl();
        showjam();
        pesanan = new mpesanan();
        idpesanan = pesanan.getidpesanan();
    }

    public void showtgl() {
        Date d = new Date();
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        boxtgl.setText(df.format(d));
    }

    public void showjam() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat df = new SimpleDateFormat("hh:mm:ss a");
                boxjam.setText(df.format(d));
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupmenu = new javax.swing.ButtonGroup();
        panelmenu = new javax.swing.JPanel();
        seblak_original = new javax.swing.JRadioButton();
        seblakmi = new javax.swing.JRadioButton();
        mi_goreng = new javax.swing.JRadioButton();
        seblak_bakso = new javax.swing.JRadioButton();
        pillevel = new javax.swing.JComboBox<>();
        paneltoping = new javax.swing.JPanel();
        pil1 = new javax.swing.JCheckBox();
        pil2 = new javax.swing.JCheckBox();
        pil3 = new javax.swing.JCheckBox();
        pil4 = new javax.swing.JCheckBox();
        pil5 = new javax.swing.JCheckBox();
        pil6 = new javax.swing.JCheckBox();
        pil7 = new javax.swing.JCheckBox();
        pil8 = new javax.swing.JCheckBox();
        pil13 = new javax.swing.JCheckBox();
        pil14 = new javax.swing.JCheckBox();
        pil15 = new javax.swing.JCheckBox();
        pil12 = new javax.swing.JCheckBox();
        pil11 = new javax.swing.JCheckBox();
        pil10 = new javax.swing.JCheckBox();
        pil9 = new javax.swing.JCheckBox();
        tambah = new javax.swing.JButton();
        panelminuman = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        minuman1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        panelpesanan = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablemenu = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabeltoping = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableminuman = new javax.swing.JTable();
        btndeletemenu = new javax.swing.JButton();
        btndeletetoping = new javax.swing.JButton();
        btndeleteminuman = new javax.swing.JButton();
        boxhargatotal = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        boxkembalian = new javax.swing.JTextField();
        boxbayar = new javax.swing.JTextField();
        boxtgl = new javax.swing.JLabel();
        boxjam = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelmenu.setBackground(new java.awt.Color(255, 153, 51));
        panelmenu.setOpaque(false);
        panelmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        groupmenu.add(seblak_original);
        seblak_original.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seblak_original.setText("seblak original 7k");
        seblak_original.setOpaque(false);
        seblak_original.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seblak_originalActionPerformed(evt);
            }
        });
        panelmenu.add(seblak_original, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        groupmenu.add(seblakmi);
        seblakmi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seblakmi.setText("seblakmi 10k");
        seblakmi.setOpaque(false);
        seblakmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seblakmiActionPerformed(evt);
            }
        });
        panelmenu.add(seblakmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        groupmenu.add(mi_goreng);
        mi_goreng.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mi_goreng.setText("mi goreng 12k");
        mi_goreng.setOpaque(false);
        mi_goreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_gorengActionPerformed(evt);
            }
        });
        panelmenu.add(mi_goreng, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        groupmenu.add(seblak_bakso);
        seblak_bakso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seblak_bakso.setText("seblak bakso 20k");
        seblak_bakso.setOpaque(false);
        seblak_bakso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seblak_baksoActionPerformed(evt);
            }
        });
        panelmenu.add(seblak_bakso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        pillevel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pillevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "level 1", "level 2", "level 3", "level 4", "level 5" }));
        pillevel.setOpaque(false);
        panelmenu.add(pillevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        getContentPane().add(panelmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 510, 290));

        paneltoping.setBackground(new java.awt.Color(255, 153, 51));
        paneltoping.setOpaque(false);
        paneltoping.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pil1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pil1.setText("susu");
        pil1.setOpaque(false);
        paneltoping.add(pil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        pil2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pil2.setText("bakso");
        pil2.setOpaque(false);
        paneltoping.add(pil2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        pil3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pil3.setText("makaroni");
        pil3.setOpaque(false);
        paneltoping.add(pil3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        pil4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pil4.setText("spageti");
        pil4.setOpaque(false);
        paneltoping.add(pil4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        pil5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pil5.setText("mi");
        pil5.setOpaque(false);
        paneltoping.add(pil5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        pil6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pil6.setText("cilot");
        pil6.setOpaque(false);
        paneltoping.add(pil6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        pil7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pil7.setText("krupuk");
        pil7.setOpaque(false);
        paneltoping.add(pil7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        pil8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pil8.setText("ceker");
        pil8.setOpaque(false);
        paneltoping.add(pil8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        pil13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pil13.setText("somay");
        pil13.setOpaque(false);
        paneltoping.add(pil13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        pil14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pil14.setText("jeroan");
        pil14.setOpaque(false);
        paneltoping.add(pil14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        pil15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pil15.setText("kerang");
        pil15.setOpaque(false);
        paneltoping.add(pil15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        pil12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pil12.setText("cumi");
        pil12.setOpaque(false);
        paneltoping.add(pil12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        pil11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pil11.setText("ikan");
        pil11.setOpaque(false);
        paneltoping.add(pil11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        pil10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pil10.setText("daging");
        pil10.setOpaque(false);
        paneltoping.add(pil10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        pil9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pil9.setText("tulang");
        pil9.setOpaque(false);
        paneltoping.add(pil9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        getContentPane().add(paneltoping, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 350, 290));

        tambah.setText("tambah");
        tambah.setEnabled(false);
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 100, 50));

        panelminuman.setBackground(new java.awt.Color(51, 255, 51));
        panelminuman.setOpaque(false);
        panelminuman.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("minuman 10");
        panelminuman.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 90, 70));

        minuman1.setText("minuman 1");
        minuman1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minuman1ActionPerformed(evt);
            }
        });
        panelminuman.add(minuman1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 70));

        jButton4.setText("minuman 2");
        panelminuman.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 90, 70));

        jButton5.setText("minuman 3");
        panelminuman.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 90, 70));

        jButton6.setText("minuman 4");
        panelminuman.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 90, 70));

        jButton7.setText("miuman 5");
        panelminuman.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 90, 70));

        jButton8.setText("minuman 6");
        panelminuman.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 90, 70));

        jButton9.setText("minuman 7");
        panelminuman.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 90, 70));

        jButton10.setText("minuman 8");
        panelminuman.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 90, 70));

        jButton11.setText("minuman 9");
        panelminuman.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 90, 70));

        getContentPane().add(panelminuman, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 110, 430, 300));

        panelpesanan.setBackground(new java.awt.Color(51, 255, 51));
        panelpesanan.setOpaque(false);
        panelpesanan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablemenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id_pesan", "nama_menu", "level"
            }
        ));
        tablemenu.setOpaque(false);
        tablemenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablemenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablemenu);
        if (tablemenu.getColumnModel().getColumnCount() > 0) {
            tablemenu.getColumnModel().getColumn(0).setMinWidth(70);
            tablemenu.getColumnModel().getColumn(0).setMaxWidth(20);
            tablemenu.getColumnModel().getColumn(2).setMinWidth(50);
            tablemenu.getColumnModel().getColumn(2).setMaxWidth(50);
        }

        panelpesanan.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 320, 200));

        tabeltoping.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabeltoping.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id_pesan_toping", "nama_toping"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabeltoping.setOpaque(false);
        tabeltoping.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeltopingMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabeltoping);

        panelpesanan.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 240, 220));

        tableminuman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id_pesan", "nama_minuman"
            }
        ));
        tableminuman.setOpaque(false);
        tableminuman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableminumanMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableminuman);

        panelpesanan.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 230, 210));

        btndeletemenu.setText("delete menu");
        btndeletemenu.setEnabled(false);
        btndeletemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletemenuActionPerformed(evt);
            }
        });
        panelpesanan.add(btndeletemenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 100, 60));

        btndeletetoping.setText("delete toping");
        btndeletetoping.setEnabled(false);
        btndeletetoping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletetopingActionPerformed(evt);
            }
        });
        panelpesanan.add(btndeletetoping, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 80, 100, 60));

        btndeleteminuman.setText("delete minuman");
        btndeleteminuman.setEnabled(false);
        btndeleteminuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteminumanActionPerformed(evt);
            }
        });
        panelpesanan.add(btndeleteminuman, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 150, 100, 60));

        getContentPane().add(panelpesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 1020, 230));

        boxhargatotal.setEditable(false);
        boxhargatotal.setBackground(new java.awt.Color(93, 68, 33));
        boxhargatotal.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        boxhargatotal.setForeground(new java.awt.Color(255, 255, 255));
        boxhargatotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        boxhargatotal.setBorder(null);
        boxhargatotal.setOpaque(false);
        boxhargatotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxhargatotalActionPerformed(evt);
            }
        });
        getContentPane().add(boxhargatotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, 370, 80));

        clear.setText("clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 90, 50));

        boxkembalian.setEditable(false);
        boxkembalian.setBackground(new java.awt.Color(93, 68, 33));
        boxkembalian.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        boxkembalian.setForeground(new java.awt.Color(255, 255, 255));
        boxkembalian.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        boxkembalian.setBorder(null);
        boxkembalian.setOpaque(false);
        boxkembalian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                boxkembalianKeyPressed(evt);
            }
        });
        getContentPane().add(boxkembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 660, 280, 60));

        boxbayar.setBackground(new java.awt.Color(93, 68, 33));
        boxbayar.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        boxbayar.setForeground(new java.awt.Color(255, 255, 255));
        boxbayar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        boxbayar.setBorder(null);
        boxbayar.setOpaque(false);
        boxbayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                boxbayarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                boxbayarKeyReleased(evt);
            }
        });
        getContentPane().add(boxbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 560, 270, 60));

        boxtgl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        boxtgl.setText("jLabel2");
        getContentPane().add(boxtgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, -1));

        boxjam.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        boxjam.setText("jLabel2");
        getContentPane().add(boxjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 140, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/transaksi.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        ArrayList<String> daftartoping = new ArrayList<String>();
        level = pillevel.getSelectedIndex() + 1;
        int menu = 0;
        if (seblak_original.isSelected()) {
            hargasatu = hargasatu + 7000;
            menu = 1;
        } else if (seblakmi.isSelected()) {
            hargasatu = hargasatu + 10000;
            menu = 2;
        } else if (mi_goreng.isSelected()) {
            hargasatu = hargasatu + 12000;
            menu = 3;
        } else if (seblak_bakso.isSelected()) {
            hargasatu = hargasatu + 20000;
            menu = 4;
        }

        if (pil1.isSelected()) {
            hargasatu = hargasatu + 2000;
            toping = true;
            daftartoping.add("1");
        }
        if (pil2.isSelected()) {
            hargasatu = hargasatu + 2000;
            toping = true;
            daftartoping.add("2");
        }
        if (pil3.isSelected()) {
            hargasatu = hargasatu + 2000;
            toping = true;
            daftartoping.add("3");
        }
        if (pil4.isSelected()) {
            hargasatu = hargasatu + 2000;
            toping = true;
            daftartoping.add("4");
        }
        if (pil5.isSelected()) {
            hargasatu = hargasatu + 2000;
            toping = true;
            daftartoping.add("5");
        }
        if (pil6.isSelected()) {
            hargasatu = hargasatu + 2000;
            toping = true;
            daftartoping.add("6");
        }
        if (pil7.isSelected()) {
            hargasatu = hargasatu + 2000;
            toping = true;
            daftartoping.add("7");
        }
        if (pil8.isSelected()) {
            hargasatu = hargasatu + 2000;
            toping = true;
            daftartoping.add("8");
        }
        if (pil9.isSelected()) {
            hargasatu = hargasatu + 2000;
            toping = true;
            daftartoping.add("9");
        }
        if (pil10.isSelected()) {
            hargasatu = hargasatu + 2000;
            toping = true;
            daftartoping.add("10");
        }
        if (pil11.isSelected()) {
            hargasatu = hargasatu + 2000;
            toping = true;
            daftartoping.add("11");
        }
        if (pil12.isSelected()) {
            hargasatu = hargasatu + 2000;
            toping = true;
            daftartoping.add("12");
        }
        if (pil13.isSelected()) {
            hargasatu = hargasatu + 2000;
            toping = true;
            daftartoping.add("13");
        }
        if (pil14.isSelected()) {
            hargasatu = hargasatu + 2000;
            toping = true;
            daftartoping.add("14");
        }
        if (pil15.isSelected()) {
            hargasatu = hargasatu + 2000;
            toping = true;
            daftartoping.add("15");
        }

        System.out.println("idtoping sebelum" + idtoping);
        if (toping) {
            inserttoping(daftartoping);
            insertmenu("" + menu);
        } else {
            insertmenutanpatoping("" + menu);
        }
        System.out.println("idtoping sesudah" + idtoping);
        idtoping = null;
        hargatotal = hargatotal + hargasatu;
        hargasatu = 0;
        refreshtable();
        clear();
    }//GEN-LAST:event_tambahActionPerformed
    public void insertmenu(String id) {
        //data[0]=id_pesanan
        //data[1]=id_menu
        //data[2]=id_toping
        //data[3]=level
        //data[4]=harga_bayar
        String data[] = {"" + idpesanan, id, idtoping, "" + level, "" + hargasatu};
        if (pesanan.tambahpesananmakan(data)) {
        } else {
            message("gagal insert makanan");
        }
    }

    public void insertmenutanpatoping(String id) {
        //data[0]=id_pesanan
        //data[1]=id_menu
        //data[2]=id_toping
        //data[3]=level
        //data[4]=harga_bayar
        String data[] = {"" + idpesanan, id, "" + level, "" + hargasatu};
        if (pesanan.tambahpesananmakantanpatoping(data)) {
        } else {
            message("gagal insert makanan");
        }
        toping = false;
    }

    public void inserttoping(ArrayList id) {
        idtoping = pesanan.getidtoping();
        for (int i = 0; i < id.size(); i++) {
            if (pesanan.tambahtoping(idtoping, id.get(i).toString())) {
            } else {
                message("gagal insert toping");
            }
        }

    }

    public void clear() {
        tambah.setEnabled(false);
        groupmenu.clearSelection();
        pil1.setSelected(false);
        pil2.setSelected(false);
        pil3.setSelected(false);
        pil4.setSelected(false);
        pil5.setSelected(false);
        pil6.setSelected(false);
        pil7.setSelected(false);
        pil8.setSelected(false);
        pil9.setSelected(false);
        pil10.setSelected(false);
        pil11.setSelected(false);
        pil12.setSelected(false);
        pil13.setSelected(false);
        pil14.setSelected(false);
        pil15.setSelected(false);
        pillevel.setSelectedIndex(0);
    }
    private void boxhargatotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxhargatotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxhargatotalActionPerformed

    private void seblakmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seblakmiActionPerformed
        tambah.setEnabled(true);
    }//GEN-LAST:event_seblakmiActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        boxhargatotal.setText("");
        hargatotal = 0;
        clear();
    }//GEN-LAST:event_clearActionPerformed

    private void seblak_originalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seblak_originalActionPerformed
        tambah.setEnabled(true);
    }//GEN-LAST:event_seblak_originalActionPerformed

    private void mi_gorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_gorengActionPerformed
        tambah.setEnabled(true);
    }//GEN-LAST:event_mi_gorengActionPerformed

    private void seblak_baksoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seblak_baksoActionPerformed
        tambah.setEnabled(true);
    }//GEN-LAST:event_seblak_baksoActionPerformed

    private void minuman1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minuman1ActionPerformed
        String data[] = {idpesanan, "1", "10000"};
        pesanan.tambahpesananminum(data);
        refreshtable();
    }//GEN-LAST:event_minuman1ActionPerformed

    private void tablemenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablemenuMouseClicked
        btndeletemenu.setEnabled(true);
        btndeleteminuman.setEnabled(false);
        btndeletetoping.setEnabled(false);
        try {
            String idtoping = tablemenu.getValueAt(tablemenu.getSelectedRow(), 3).toString();
            tabeltoping.setModel(pesanan.gettoping(idtoping));
        } catch (Exception ex) {
            cleartable(tabeltoping);
        }
    }//GEN-LAST:event_tablemenuMouseClicked

    private void btndeleteminumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteminumanActionPerformed
        String idminuman = tableminuman.getValueAt(tableminuman.getSelectedRow(), 0).toString();
        if (pesanan.delete(idminuman)) {
            message("minuman di hapus");
        } else {
            message("gagal hapus");
        }
        refreshtable();
    }//GEN-LAST:event_btndeleteminumanActionPerformed

    private void btndeletetopingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletetopingActionPerformed
        String idtoping = tabeltoping.getValueAt(tabeltoping.getSelectedRow(), 0).toString();
        if (pesanan.deletetoping(idtoping)) {
            String nama_toping = tabeltoping.getValueAt(tabeltoping.getSelectedRow(), 1).toString();
            String id_pesanan_toping = tablemenu.getValueAt(tablemenu.getSelectedRow(), 3).toString();
            if (pesanan.updateharga(nama_toping, id_pesanan_toping, idpesanan)) {
                message("toping di hapus");
            } else {
                message("gagal ngurangi");
            }
        } else {
            message("gagal hapus");
        }
        refreshtable();
    }//GEN-LAST:event_btndeletetopingActionPerformed

    private void btndeletemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletemenuActionPerformed
        String idmenu = tablemenu.getValueAt(tablemenu.getSelectedRow(), 0).toString();
        if (pesanan.delete(idmenu)) {
            message("menu di hapus");
        } else {
            message("gagal hapus");
        }
        refreshtable();
    }//GEN-LAST:event_btndeletemenuActionPerformed

    private void tabeltopingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeltopingMouseClicked
        btndeletemenu.setEnabled(false);
        btndeleteminuman.setEnabled(false);
        btndeletetoping.setEnabled(true);
    }//GEN-LAST:event_tabeltopingMouseClicked

    private void tableminumanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableminumanMouseClicked
        btndeletemenu.setEnabled(false);
        btndeleteminuman.setEnabled(true);
        btndeletetoping.setEnabled(false);
    }//GEN-LAST:event_tableminumanMouseClicked

    private void boxkembalianKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boxkembalianKeyPressed

    }//GEN-LAST:event_boxkembalianKeyPressed

    private void boxbayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boxbayarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !boxbayar.getText().equals("")) {
            double uangbayar = Double.parseDouble(boxbayar.getText());
            if (uangbayar < hargatotal) {
                message("uangkurang");
            } else {
                cetak();
                cleartable(tablemenu);
                cleartable(tableminuman);
                cleartable(tabeltoping);
                popupkembalian.setkembalian(boxkembalian.getText());
                boxbayar.setText("");
                boxkembalian.setText("");
                clear();
                idpesanan = pesanan.getidpesanan();
            }
        }
    }//GEN-LAST:event_boxbayarKeyPressed
    public void cetak() {
        String bayar = rubahuang(Double.parseDouble(boxbayar.getText()));
        try {

            File file = new File("src/report/strukjual.jrxml");
            try {
                jasperDesign = JRXmlLoader.load(file);
                param.clear();
                param.put("tgl", boxtgl.getText());
                param.put("jam", boxjam.getText());
                param.put("id_pesanan", idpesanan);
                param.put("kembalian", boxkembalian.getText());
                param.put("totalharga", boxhargatotal.getText());
                param.put("totalbayar", bayar);
                jasperReport = JasperCompileManager.compileReport(jasperDesign);
                jasperPrint = JasperFillManager.fillReport(jasperReport, param, pesanan.getConnection());
//                JasperViewer.viewReport(jasperPrint, true);
                JasperPrintManager.printReport(jasperPrint, false);
            } catch (Exception e) {
                e.printStackTrace();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Dokumen Tidak Ada" + ex);
            ex.printStackTrace();
        }

    }
    private void boxbayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boxbayarKeyReleased
        try {
            if (!boxbayar.getText().equals("")) {
                double uangbayar = Double.parseDouble(boxbayar.getText());
                if (uangbayar < hargatotal) {
                    boxkembalian.setBackground(Color.red);
                    boxkembalian.setText("uang kurang");
                } else {
                    boxkembalian.setBackground(Color.green);
                    double kembalian = uangbayar - hargatotal;
                    boxkembalian.setText("" + rubahuang(kembalian));
                }
            }
        } catch (Exception e) {
            message("periksa kembali inputan anda");
            e.printStackTrace();
            boxbayar.setText("");
        }

    }//GEN-LAST:event_boxbayarKeyReleased
    public String rubahuang(double uang) {
        String mataUang = String.format("Rp.%,.0f", uang).replaceAll(",", ".") + ",00";
        System.out.println("uang"+mataUang);
        return mataUang;

    }

    public void refreshtable() {
        try {
            System.out.println("dapat id pesana" + idpesanan);
            tablemenu.setModel(pesanan.cekpesananmakanan(idpesanan));
            tableminuman.setModel(pesanan.cekpesananminuman(idpesanan));
            tabeltoping.setModel(pesanan.gettoping(idtoping));
            String uang = pesanan.getuangbayar(idpesanan);
            hargatotal = Double.parseDouble(pesanan.getuangbayarasli(idpesanan));
            boxhargatotal.setText(uang);
        } catch (SQLException ex) {
            Logger.getLogger(pesananflow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void cleartable(JTable table) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        table.setModel(model);
    }

    public void message(String txt) {
        JOptionPane.showMessageDialog(null, txt, "error", JOptionPane.OK_OPTION);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pesananflow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pesananflow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pesananflow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pesananflow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new pesananflow().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(pesananflow.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField boxbayar;
    private javax.swing.JTextField boxhargatotal;
    private javax.swing.JLabel boxjam;
    private javax.swing.JTextField boxkembalian;
    private javax.swing.JLabel boxtgl;
    private javax.swing.JButton btndeletemenu;
    private javax.swing.JButton btndeleteminuman;
    private javax.swing.JButton btndeletetoping;
    private javax.swing.JButton clear;
    private javax.swing.ButtonGroup groupmenu;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton mi_goreng;
    private javax.swing.JButton minuman1;
    private javax.swing.JPanel panelmenu;
    private javax.swing.JPanel panelminuman;
    private javax.swing.JPanel panelpesanan;
    private javax.swing.JPanel paneltoping;
    private javax.swing.JCheckBox pil1;
    private javax.swing.JCheckBox pil10;
    private javax.swing.JCheckBox pil11;
    private javax.swing.JCheckBox pil12;
    private javax.swing.JCheckBox pil13;
    private javax.swing.JCheckBox pil14;
    private javax.swing.JCheckBox pil15;
    private javax.swing.JCheckBox pil2;
    private javax.swing.JCheckBox pil3;
    private javax.swing.JCheckBox pil4;
    private javax.swing.JCheckBox pil5;
    private javax.swing.JCheckBox pil6;
    private javax.swing.JCheckBox pil7;
    private javax.swing.JCheckBox pil8;
    private javax.swing.JCheckBox pil9;
    private javax.swing.JComboBox<String> pillevel;
    private javax.swing.JRadioButton seblak_bakso;
    private javax.swing.JRadioButton seblak_original;
    private javax.swing.JRadioButton seblakmi;
    private javax.swing.JTable tabeltoping;
    private javax.swing.JTable tablemenu;
    private javax.swing.JTable tableminuman;
    private javax.swing.JButton tambah;
    // End of variables declaration//GEN-END:variables
}
